__author__ = 'Cami'
from django.conf.urls import patterns, url
from netdev import views
from django.conf import settings

urlpatterns = patterns('netdev.views',
        url(r'^dados/$', 'data', name='data'),
        url(r'^aceitacao/$', 'acceptance', name='acceptance'),
        url(r'^meu_repositorio/$', 'repository_index', name='repository_index'),
        url(r'^adicionar_arquivo/$', 'add_file', name='add_file'),
        url(r'^novo_diretorio/$', 'add_filecat', name='add_filecat'),
        url(r'^diretorio/(?P<cat_id>\d+)/deletar/$', 'cat_delete', name='category_delete'),
        url(r'^diretorio/(?P<cat_id>\d+)/editar/$', 'cat_edit', name='category_edit'),
        url(r'^diretorio/(?P<cat_id>\d+)/$', 'cat_show', name='category_view'),
        url(r'^diretorios/', 'filecat_all', name='category_list'),
        url(r'^arquivo/(?P<file_id>\d+)/deletar/$', 'delete_file', name='delete_file'),
        url(r'^arquivo/(?P<file_id>\d+)/editar/$', 'edit_file', name='edit_file'),
        url(r'^arquivo/(?P<file_id>\d+)/$', 'view_file', name='view_file'),
        url(r'^$', views.index, name='index'),
        url(r'^sobre/$', views.about, name='about'),
        url(r'^repositorios/$', views.repositorys, name='repositorys'),
        url(r'^usuarios/$', views.users, name='users'),
   #     url(r'^pesquisar/$', views.search, name='search'),
        url(r'^perfil/(?P<username>\w+)/$', views.public_profile, name='public_profile'),
        url(r'^perfil/(?P<username>\w+)/adicionado/$', views.confirm_friendship, name='confirm_friendship'),
        url(r'^perfil/(?P<username>\w+)/removido/$', views.remove_friendship, name='remove_friendship'),
        url(r'^perfil/(?P<username>\w+)/amigos/$', views.profile_friends, name='profile_friends'),
        url(r'^perfil/(?P<username>\w+)/repositorio/$', views.profile_repository, name='public_repository'),
    #    url(r'^perfil/(?P<username>\w+)/topicos/$', views.profile_topics, name='profile_topics'),
        url(r'^perfil/(?P<username>\w+)/status/$', views.profile_status, name='profile_status'),
        url(r'^editar_status/(?P<update_id>\w+)/$', views.edit_status, name='edit_status'),
        url(r'^remover_status/(?P<update_id>\w+)/$', views.remove_status, name='remove_status'),
    #    url(r'^perfil/(?P<username>\w+)/repositorio/$', views.profile_repositorys, name='profile_repositorys'),
        url(r'^mudar_perfil/$', views.change_profile, name='change_profile'),
        url(r'^minha_conta/mudar_senha/$', views.change_password, name='change_password'),
        url(r'^minha_conta/desativar/confirmacao/$', views.deactivate_account, name='deactivate_account'),
        url(r'^minha_conta/desativar/$', views.check_account, name='check_account'),
        url(r'^minha_conta/editar/$', views.edit_account, name='edit_account'),
        url(r'^minha_conta/$', views.view_account, name='view_account'),
    #    url(r'^amigos/$', views.friends, name='friends'),
        url(r'^meus_topicos/$', views.my_topics, name='my_topics'),
        url(r'^caixa_de_entrada/$', views.inbox, name='inbox'),
        url(r'^caixa_de_saida/$', views.outbox, name='outbox'),
        url(r'^lixeira/$', views.trash, name='trash'),
        url(r'^nova_mensagem/sucesso/$', views.confirm_message, name='confirm_message'),
        url(r'^nova_mensagem/$', views.new_message, name='new_message'),
        url(r'^mensagem/(?P<message_id>\w+)/$', views.message, name='message'),
        url(r'^registrar', views.register, name='register'),
        url(r'^entrar/$', views.user_login, name='login'),
      #  url(r'^restrito/', views.restricted, name='restricted'),
        url(r'^forum/$', views.foruns, name='foruns'),
        url(r'^sair/$', views.user_logout, name='logout'),
        url(r'^forum/(?P<forum_name_url>\w+)/$', views.forum, name='forum'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/novo_topico/$', views.add_topic, name='add_topic'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/nova_resposta/$', views.add_post, name='add_post'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/$', views.subforum, name='subforum'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/$', views.category, name='category'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/$', views.topic, name='topic'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/editar_topico/$', views.edit_topic, name='edit_topic'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/editar_resposta/$', views.edit_post, name='edit_post'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/remover_topico/$', views.remove_topic, name='remove_topic'),
        url(r'^forum/(?P<forum_name_url>\w+)/(?P<subforum_name_url>\w+)/(?P<category_name_url>\w+)/(?P<topic_id>\w+)/remover_resposta/$', views.remove_post, name='remove_post'),
    )

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )
